### PR TITLE
Increase minimum Go version to 1.22

### PR DESCRIPTION
**Pull request by adrianreber**
1.22 is the minimum version required by a couple of dependencies.

### CODE REVIEW

**Comment by snprajwal** [comment]
Might it make sense to squash the latest commit with the first one (with the Go version bump)? It'll ensure we can bisect the repo going forward

**Comment by rst0git** [comment]
LGTM

Would it be possible to add more information about the dependencies that require 1.22 in the commit message?

**Comment by adrianreber** [comment]
> LGTM
> 
> Would it be possible to add more information about the dependencies that require 1.22 in the commit message?

I don't really know. I just see dependabot failing with a diff that indicates that 1.22 is required.

**Comment by rst0git** [comment]
It looks like [k8s.io/api](https://github.com/kubernetes/api) is one of these dependencies:
- https://github.com/kubernetes/api/commit/b374e580f9e2820e0870f45715ab92e2916f0664
- https://github.com/kubernetes/kubelet/commit/8ce7a49ca85885ce6ce6f26ef206be17979d8623

**Comment by adrianreber** [comment]
@rst0git Added k8s.io/api to the commit message.

@snprajwal squashed

**Review by snprajwal — APPROVED** [review]

**Review by rst0git — APPROVED** [review]

**Pull request merged**
