### PR TITLE
Update controller-manager to Allow Operator Access to Checkpoints

### PR DESCRIPTION
**Pull request by Parthiba-Hazra**
Update controller-manager with necessary securityContext to allow privileged access needed for checkpoint management and added volume mount for /var/lib/kubelet/checkpoints to the manager container.

### CODE REVIEW

**Comment by adrianreber** [comment]
This looks reasonable. Works for me.

@snprajwal @rst0git what do you think

**Comment by adrianreber** [comment]
@Parthiba-Hazra a new PR to introduce some CI run would be helpful at this point. That means installing Kubernetes. I am mostly using it directly from git. In this case this probably not necessary.

**Comment by snprajwal** [comment]
LGTM, but like @adrianreber mentioned, we should probably figure out a good way to test this. I think we can try using kind to create a single-node cluster and test on that in the CI. Might have to fiddle with the permissions on Github CI runners, but it should be feasible

**Comment by rst0git** [comment]
> I think we can try using kind to create a single-node cluster and test on that in the CI.

The following looks like a good example:
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/.github/workflows/quickstart.yml

**Comment by adrianreber** [comment]
Thanks @rst0git. Let's do the CI changes in another PR.

**Pull request merged**
